version: 3
image: CentOs:7.1.1503
stages:
- build
- test
构建任务:
  stage: build
  job_type: image_build
  only:
    branches:
    - hexo
  build_dir: /
  cache: true
  dockerfile_path: /Dockerfile
布署任务:
  stage: test
  job_type: test
  only:
    branches:
    - hexo
  pull_request: false
  dependencies:
  - 构建任务
  before_script:
  - mkdir ~/.ssh
  - mv .daocloud/id_rsa ~/.ssh/id_rsa
  - mv .daocloud/ssh_config ~/.ssh/config
  - mv .daocloud/known_hosts ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/config
  - chmod 600 ~/.ssh/known_hosts
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - rm -rf .daocloud
  - git config --global user.name "fulndon"
  - git config --global user.email "1021131482@qq.com"
  image: daocloud.io/fulndon/wolf:latest
  install:
  - npm install
  script:
  - hexo clean
  - hexo g
  - hexo d
  - rm -rf ~/.ssh/
